"""empty message

Revision ID: ea1b62d5bf28
Revises: 
Create Date: 2022-06-12 08:58:23.294023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea1b62d5bf28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('subject_name', sa.String(length=200), nullable=False))
    op.drop_column('subject', 'user_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('user_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('subject', 'subject_name')
    # ### end Alembic commands ###
